### ISSUE TITLE
"Attempted an unsupported operation" when trying to open Settings

### ISSUE THREAD

**Issue by wasivis** [DavidKinder/Windows-Glulxe#4]
Everytime I try to open **Settings** or **About Gluxle**, an alert pops up saying "**Attempted an unsupported operation**", then the software closes. I can play games, and open Help, About this game and Scroll Buffer without problems.

![screenshot](https://user-images.githubusercontent.com/87397558/234714193-c0007eee-7c85-490e-9cd6-a4fa4584bce7.png)

**Comment by DavidKinder** [comment]
The problem is that the translation DLLs didn't get rebuilt properly. I will do a new build shortly that will fix this. In the meantime, I've attached an updated Spanish translation DLL: if you unzip it and overwrite the existing one with this, all the dialogs should work for you.
[GlkEspañol.zip](https://github.com/DavidKinder/Windows-Glulxe/files/11340593/GlkEspanol.zip)

**Comment by wasivis** [comment]
It works, thank you so much! Question, one of the reasons I wanted to get to Settings was so I could change the language to English, but I'm not seeing an option. Is it possible? Either way, everything works properly now, so thank you again! :)

**Comment by DavidKinder** [comment]
You can't change the language from Settings, it is just picked up from the Windows settings. But if you want English, remove the translation DLLs (GlkEspañol.dll etc.). Without those DLLs present the UI will just be in English.

**Comment by wasivis** [comment]
Perfect, thank you!

**Comment by DavidKinder** [comment]
A new build of Windows Glulxe, 0.60.153, has been released that fixes this problem, see https://github.com/DavidKinder/Windows-Glulxe/releases/tag/0.6.0.153
